CREATE SCHEMA IF NOT EXISTS `bdproyectop312022` DEFAULT CHARACTER SET utf8 ;
USE `bdproyectop312022` ;

CREATE TABLE IF NOT EXISTS usuario (
  id_usuario INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(60) NOT NULL,
  password VARCHAR(25)NOT NULL,
  PRIMARY KEY (id_usuario) )
ENGINE = InnoDB CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS modelo (
  Id_Modulo INT NOT NULL AUTO_INCREMENT,
  Codigo VARCHAR(60) NOT NULL,
  Nombre VARCHAR(60) NOT NULL,
  Estatus VARCHAR(60) NOT NULL,
  PRIMARY KEY (Id_Modulo) )
ENGINE = InnoDB CHARACTER SET = latin1;
